version: '3.8'

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://model:8000
      - APP_VERSION=1.0.0-compose
    depends_on:
      - model
    restart: unless-stopped
